package com.example.vpn.ui.main

enum class Status(val value: String) {
    CONNECT("CONNECT"),
    CONNECTING("CONNECTING"),
    CONNECTED("CONNECTED"),
    TRY_DIFFERENT_SERVER("TRY_DIFFERENT_SERVER"),
    LOADING("LOADING"),
    INVALID_DEVICE("INVALID_DEVICE"),
    AUTHENTICATION_CHECK("AUTHENTICATION_CHECK")
}